Repository JozefStefanInstitute/eLENS-miner-system, pull requests merged in 2020-01, with the labels that each got.

#8 Configured database connection
  .gitignore
  document_similarity/microservice/__init__.py
  document_similarity/microservice/config/config_db.py
  document_similarity/microservice/routes/service.py
  entrypoint/microservice/__init__.py
  entrypoint/microservice/config/config_db.py
  entrypoint/microservice/routes/database.py
  entrypoint/microservice/routes/document_retrieval.py
  entrypoint/microservice/routes/service.py
Labels: bug

#11 Add and restructure files for github automatization
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: enhancement

#12 Modify readme documentation and acknowledgements
  README.md
  document_retrieval/README.md
  document_retrieval/microservice/__init__.py
  document_retrieval/microservice/config/README.md
  document_retrieval/microservice/config/config.py
  document_retrieval/microservice/config/config_db.py
  document_retrieval/microservice/config/config_logging.py
  document_retrieval/microservice/library/README.md
  document_retrieval/microservice/library/documentRetrieval.py
  document_retrieval/microservice/library/formatter.py
  document_retrieval/microservice/library/logger.py
  document_retrieval/microservice/library/postgresql.py
  document_retrieval/microservice/main.py
  document_retrieval/microservice/routes/README.md
  document_retrieval/microservice/routes/error_handlers.py
  document_retrieval/microservice/routes/index.py
  document_retrieval/microservice/routes/service.py
  document_retrieval/microservice/static/css/bs/bootstrap-grid.css
  document_retrieval/microservice/static/css/bs/bootstrap-grid.css.map
  document_retrieval/microservice/static/css/bs/bootstrap-grid.min.css
  document_retrieval/microservice/static/css/bs/bootstrap-grid.min.css.map
  document_retrieval/microservice/static/css/bs/bootstrap-reboot.css
  document_retrieval/microservice/static/css/bs/bootstrap-reboot.css.map
  document_retrieval/microservice/static/css/bs/bootstrap-reboot.min.css
  document_retrieval/microservice/static/css/bs/bootstrap-reboot.min.css.map
  document_retrieval/microservice/static/css/bs/bootstrap.css
  document_retrieval/microservice/static/css/bs/bootstrap.css.map
  document_retrieval/microservice/static/css/bs/bootstrap.min.css
  document_retrieval/microservice/static/css/bs/bootstrap.min.css.map
  document_retrieval/microservice/static/css/index.css
  document_retrieval/microservice/static/js/common.js
  document_retrieval/microservice/templates/index.html
  document_similarity/README.md
  entrypoint/README.md
  text_embeddings/README.md
Labels: documentation

#21 bugfixes to document retrieval microservice
  README.md
  document_retrieval/microservice/config/config.py
  document_retrieval/microservice/library/document_retrieval.py
  document_retrieval/microservice/main.py
  document_retrieval/microservice/routes/service.py
Labels: bug

#23 Added ECOLEX crawling scripts together with instructions
  .gitignore
  crawlers/ecolex/README.md
  crawlers/ecolex/get_content_jurisprudence.py
  crawlers/ecolex/get_content_legislation.py
  crawlers/ecolex/get_content_literature.py
  crawlers/ecolex/get_content_treaties.py
  crawlers/ecolex/get_content_treaty_decisions.py
  crawlers/ecolex/get_main_links.py
  crawlers/ecolex/helper_functions.py
  crawlers/ecolex/jurisprudence/.gitkeep
  crawlers/ecolex/legislation/.gitkeep
  crawlers/ecolex/literature/.gitkeep
  crawlers/ecolex/main_links_SLO_sample.txt
  crawlers/ecolex/requirements.txt
  crawlers/ecolex/start_crawling.py
  crawlers/ecolex/treaty decisions/.gitkeep
  crawlers/ecolex/treaty/.gitkeep
  crawlers/eurlex/.gitkeep
Labels: enhancement
